/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Returns immutable build/runtime facts required to bootstrap the renderer.
 */
async bootstrapGetState() : Promise<Result<BootstrapState, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bootstrap_get_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultInitialize(request: InitializeVaultRequest) : Promise<Result<VaultSummary, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_initialize", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultStatus() : Promise<Result<VaultStatusView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startupRecoveryRun() : Promise<Result<StartupRecoveryReport, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("startup_recovery_run") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startupRecoveryStatus() : Promise<Result<StartupRecoveryReport, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("startup_recovery_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts the configured Universal global scan without mutating its source root.
 */
async scanStart(request: ScanRequest) : Promise<Result<JobRef, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_start", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the authoritative state of one scan job.
 */
async scanGet(jobId: string) : Promise<Result<ScanRunView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_get", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Requests cooperative cancellation at the next safe candidate boundary.
 */
async scanCancel(jobId: string) : Promise<Result<CancelResult, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_cancel", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists paginated external Library items from the Rust-owned reconciliation model.
 */
async libraryList(query: LibraryQuery) : Promise<Result<LibraryPage, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_list", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async targetRegisterFixture(request: RegisterTargetRequest) : Promise<Result<TargetView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("target_register_fixture", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async targetsList() : Promise<Result<TargetView[], AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("targets_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deploymentPlan(request: DeploymentPlanRequest) : Promise<Result<DeploymentPlanView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("deployment_plan", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async batchDeploymentPlan(request: BatchDeploymentPlanRequest) : Promise<Result<BatchDeploymentPlanView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_deployment_plan", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deploymentUndoPlan(request: OperationIdRequest) : Promise<Result<BatchDeploymentPlanView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("deployment_undo_plan", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async undeployPlan(request: UndeployPlanRequest) : Promise<Result<DeploymentPlanView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undeploy_plan", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deploymentVerify(request: DeploymentIdRequest) : Promise<Result<DeploymentHealthView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("deployment_verify", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deploymentsList(query: DeploymentQuery) : Promise<Result<DeploymentPage, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("deployments_list", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async takeoverKeepExternal(request: KeepExternalRequest) : Promise<Result<KeepExternalResult, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("takeover_keep_external", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async takeoverPlan(request: TakeoverPlanRequest) : Promise<Result<TakeoverPlanView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("takeover_plan", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async operationExecute(request: ExecuteOperationRequest) : Promise<Result<AnyOperationView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("operation_execute", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async operationCancel(request: OperationIdRequest) : Promise<Result<OperationCancelResult, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("operation_cancel", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async operationGet(request: OperationIdRequest) : Promise<Result<AnyOperationView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("operation_get", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async skillGet(request: SkillIdRequest) : Promise<Result<SkillDetail, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("skill_get", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async skillPreviewFile(request: SkillPreviewRequest) : Promise<Result<TextPreview, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("skill_preview_file", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async activityList(query: ActivityQuery) : Promise<Result<ActivityItem[], AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activity_list", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async activityDetail(id: string) : Promise<Result<ActivityDetail, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activity_detail", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
domainInvalidated: DomainInvalidated,
scanProgress: ScanProgress
}>({
domainInvalidated: "domain-invalidated",
scanProgress: "scan-progress"
})

/** user-defined constants **/



/** user-defined types **/

export type ActivityDetail = { item: ActivityItem; detailsJson: string; operation: ActivityOperationEvidence | null; scan: ActivityScanEvidence | null }
export type ActivityItem = { id: string; kind: string; state: string; outcome: string | null; summary: string; startedAt: string; completedAt: string | null; operationId: string | null; scanRunId: string | null }
export type ActivityOperationEvidence = { recoveryAvailable: boolean; errorCode: string | null; failedStep: number | null; planReference: string; journalReference: string; recoveryReferences: string[]; paths: ActivityPathEvidence[] }
export type ActivityPathEvidence = { stepOrder: number; path: string; requestedMode: string | null; resolvedMode: string | null; stagePath: string | null; backupPath: string | null; rollbackPath: string | null }
export type ActivityQuery = { kind: string | null; outcome: string | null; limit: number }
export type ActivityScanEvidence = { diagnosticCount: number; errorCodes: string[] }
export type AnyOperationView = { kind: "takeover"; value: OperationView } | { kind: "deployment"; value: DeploymentOperationView } | { kind: "batch_deployment"; value: BatchDeploymentOperationView }
export type AppErrorCode = "internal" | "invalid_input" | "not_found" | "unsafe_path" | "unsupported_bundle" | "name_collision" | "stale_plan" | "operation_busy" | "cancelled" | "io_failure" | "database_failure" | "verification_failed" | "rolled_back" | "recovery_required"
export type AppErrorView = { code: AppErrorCode; title: string; message: string; retryable: boolean; recoveryAction: string | null }
export type BatchDeploymentOperationView = { operationId: string; planDigest: string; state: string; outcome: string | null; failure: string | null; recovery: string[]; review: BatchDeploymentPlanView; replayed: boolean }
export type BatchDeploymentPlanRequest = { skillId: string; targets: BatchDeploymentTargetChoice[] }
export type BatchDeploymentPlanView = { operationId: string; planDigest: string; expiresAt: string; action: string; skillId: string; entries: DeploymentPlanView[]; recoveryCount: number; consequence: string }
export type BatchDeploymentTargetChoice = { targetId: string; requestedMode: DeploymentModeDto | null }
export type BootstrapState = { appName: string; appVersion: string; bundleIdentifier: string; contractVersion: number; implementationStage: string; vaultInitialized: boolean; vaultPath: string | null; runtimeStatus: RuntimeStatus; blockingWorkerLimit: number; platform: PlatformSummary }
export type CancelResult = { jobId: string; accepted: boolean }
export type DeploymentHealthView = { deploymentId: string; skillId: string; targetId: string; deploymentName: string; targetPath: string; mode: DeploymentModeDto; active: boolean; health: string; explanation: string; expectedDigest: string; vaultDigest: string | null; targetDigest: string | null; expectedLinkTarget: string | null; actualLinkTarget: string | null; driftDirection: string; allowedActions: string[]; disabledReason: string | null; verifiedAt: string }
export type DeploymentIdRequest = { deploymentId: string }
export type DeploymentModeDto = "symlink" | "managed_copy"
export type DeploymentOperationView = { operationId: string; planDigest: string; state: string; outcome: string | null; failure: string | null; recovery: string[]; review: DeploymentPlanView; replayed: boolean }
export type DeploymentPage = { items: DeploymentHealthView[]; count: number }
export type DeploymentPlanRequest = { skillId: string; targetId: string; requestedMode: DeploymentModeDto | null }
export type DeploymentPlanView = { operationId: string; planDigest: string; expiresAt: string; action: string; skillId: string; targetId: string; deploymentId: string; targetPath: string; requestedMode: DeploymentModeDto; resolvedMode: DeploymentModeDto; fallbackReason: string | null; reviewedHealth: string; noOp: boolean; consequence: string; recoveryCount: number; executionAllowed: boolean }
export type DeploymentQuery = { skillId: string | null; targetId: string | null; includeInactive: boolean; limit: number }
export type DomainInvalidated = { revision: number; scopes: string[]; ids: string[] }
export type DuplicateSummary = { exactDuplicateLocations: number; nameConflicts: number; probableDuplicatesOrRenames: number; unverified: boolean }
export type ExecuteOperationRequest = { operationId: string; planDigest: string }
},
async vaultReconcileWorking(request: SkillLifecycleRequest) : Promise<Result<ReconcileResult, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_reconcile_working", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultVerify() : Promise<Result<VaultVerifyReport, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_verify") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultRepairPlan() : Promise<Result<VaultRepairPlan, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_repair_plan") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultRepairExecute(request: ExecuteLifecycleRequest) : Promise<Result<number, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_repair_execute", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultIndexRebuildPlan() : Promise<Result<IndexRebuildPlan, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_index_rebuild_plan") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultIndexRebuildExecute(request: ExecuteLifecycleRequest) : Promise<Result<IndexRebuildResult, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_index_rebuild_execute", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultObjectGcPlan(request: ObjectGcPlanRequest) : Promise<Result<ObjectGcPlan, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_object_gc_plan", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultObjectGcExecute(request: ExecuteLifecycleRequest) : Promise<Result<ObjectGcResult, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_object_gc_execute", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultObjectGcSettings() : Promise<Result<ObjectGcSettingsSummary, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_object_gc_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultRevealWorking(request: SkillLifecycleRequest) : Promise<Result<string, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_reveal_working", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultRelocatePlan(request: VaultPathRequest) : Promise<Result<VaultRelocatePlan, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_relocate_plan", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultRelocateExecute(request: ExecuteLifecycleRequest) : Promise<Result<VaultRelocateResult, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_relocate_execute", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultOldCleanupPlan(request: VaultPathRequest) : Promise<Result<OldVaultCleanupPlan, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_old_cleanup_plan", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async vaultOldCleanupExecute(request: ExecuteLifecycleRequest) : Promise<Result<null, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("vault_old_cleanup_execute", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceRootAdd(request: WorkspaceRootAddRequest) : Promise<Result<WorkspaceRootView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_root_add", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceRootUpdate(request: WorkspaceRootUpdateRequest) : Promise<Result<WorkspaceRootView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_root_update", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceRootPause(request: WorkspaceRootPauseRequest) : Promise<Result<WorkspaceRootView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_root_pause", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceRootRemove(request: WorkspaceRootIdRequest) : Promise<Result<WorkspaceRemoveResult, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_root_remove", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceRootRescan(request: WorkspaceRootIdRequest) : Promise<Result<WorkspaceScanResultView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_root_rescan", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceRootsList() : Promise<Result<WorkspaceRootView[], AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_roots_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async manualProjectAdd(request: ManualProjectAddRequest) : Promise<Result<ManualProjectView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("manual_project_add", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async manualProjectsList() : Promise<Result<ManualProjectView[], AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("manual_projects_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async manualProjectRescan(request: ManualProjectIdRequest) : Promise<Result<WorkspaceScanResultView, AppErrorView>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("manual_project_rescan", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
export type FixtureTargetKindDto = "global" | "git_project" | "personal_project"
export type InitializeVaultRequest = { selectedDirectory: string | null }
export type JobRef = { jobId: string }
export type KeepExternalRequest = { observationId: string }
export type KeepExternalResult = { observationId: string; keptExternal: boolean }
export type LibraryAction = "keep_external" | "add_to_vault" | "add_and_manage"
export type LibraryErrorView = { code: string; summary: string }
export type LibraryFilter = "all" | "verified" | "errors" | "conflicts" | "duplicates"
export type LibraryItem = { id: string; displayName: string; deploymentName: string; ownership: LibraryOwnership; sourceSummary: string; locations: LibraryLocation[]; digest: string | null; validation: LibraryValidation; duplicateSummary: DuplicateSummary; deploymentCount: number; changedAt: string; nextActions: LibraryAction[] }
export type LibraryLocation = { observationId: string; adapterId: string; sourceRootId: string; path: string; status: string; error: LibraryErrorView | null }
export type LibraryOwnership = "external"
export type LibraryPage = { items: LibraryItem[]; total: number; offset: number; limit: number }
export type LibraryQuery = { offset: number; limit: number; search: string | null; filter: LibraryFilter }
export type LibraryValidation = "verified" | "error"
export type ObservationEvidenceView = { observationId: string; path: string; canonicalPath: string | null; digest: string | null; status: string; error: string | null }
export type OperationCancelResult = { operationId: string; cancellationRequested: boolean }
export type OperationIdRequest = { operationId: string }
export type OperationView = { operationId: string; planDigest: string; state: string; outcome: string | null; failure: string | null; recovery: string[]; context: TakeoverOperationContextView; review: TakeoverPlanView; replayed: boolean }
export type PlatformSummary = { os: string; arch: string; minimumSupportedOs: string }
export type RegisterTargetRequest = { kind: FixtureTargetKindDto; selectedDirectory: string }
export type RuntimeStatus = "ready"
export type ScanCoverageView = { state: string; complete: boolean; noFilesChanged: boolean }
export type ScanDiagnosticView = { path: string; code: string; summary: string }
export type ScanProgress = { jobId: string; phase: string; completedEntries: number; estimatedEntries: number; currentDisplayPath: string | null }
export type ScanRequest = { source: ScanSource }
export type ScanRunState = "queued" | "running" | "completed" | "completed_with_errors" | "cancelled" | "failed"
export type ScanRunView = { jobId: string; adapterId: string; sourceRootId: string; sourceName: string; displayRoot: string; state: ScanRunState; coverage: ScanCoverageView; completedEntries: number; estimatedEntries: number; observationCount: number; errorCount: number; errors: ScanDiagnosticView[]; startedAt: string; completedAt: string | null }
export type ScanSource = "universal_global"
export type SelectedLocationRequest = { observationId: string; mode: DeploymentModeDto }
export type SelectedReplacementView = { observationId: string; targetId: string; deploymentId: string; targetScope: string; path: string; requestedMode: DeploymentModeDto; resolvedMode: DeploymentModeDto; fallbackReason: string | null }
export type SkillDetail = { skillId: string; displayName: string; deploymentName: string; workingPath: string; workingDigest: string; baselineDigest: string; ownership: string; lifecycle: string; sourcePaths: string[]; deploymentPaths: string[]; observationPaths: string[]; conflicts: string[]; allowedActions: string[] }
export type SkillIdRequest = { skillId: string }
export type SkillPreviewRequest = { skillId: string; relativePath: string }
export type StartupRecoveryEvidence = { operationId: string; status: string; outcome: string | null; error: string | null }
export type StartupRecoveryReport = { completed: boolean; operations: StartupRecoveryEvidence[]; lifecycleOperations: LifecycleRecoveryEvidence[] }
export type TakeoverDecisionDto = "add_to_vault" | "add_and_manage"
export type TakeoverOperationContextView = { decision: TakeoverDecisionDto; sourceObservationId: string; skillId: string; workingPath: string; selectedObservationIds: string[] }
export type TakeoverPlanRequest = { sourceObservationId: string; decision: TakeoverDecisionDto; selectedLocations: SelectedLocationRequest[] }
export type TakeoverPlanView = { operationId: string; planDigest: string; expiresAt: string; decision: TakeoverDecisionDto; skillId: string; observations: ObservationEvidenceView[]; reviewedDigest: string; workingPath: string; baselineObjectPath: string; manifestPath: string; selectedReplacements: SelectedReplacementView[]; entryCount: number; byteCount: number; blockers: string[]; recoverySummary: string; recoveryCount: number; crossVolumeConsequence: string | null; executionAllowed: boolean }
export type TargetView = { targetId: string; adapterId: string; scope: string; projectId: string | null; projectKind: string | null; rootPath: string; isOverride: boolean; isCustom: boolean; defaultMode: DeploymentModeDto }
export type TextPreview = { skillId: string; relativePath: string; size: number; content: string }
export type UndeployPlanRequest = { deploymentId: string; resolution: UndeployResolutionDto }
export type UndeployResolutionDto = "remove_managed" | "preserve_target" | "cancel"
export type VaultStatusView = { initialized: boolean; rootPath: string | null; defaultPath: string; startupRecoveryCompleted: boolean | null }
export type VaultSummary = { rootPath: string; initialized: boolean; vaultId: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";
export type DestinationCapabilityReport = { status: CapabilityStatus; writeFile: boolean; createDirectory: boolean; symlink: boolean; executableBit: boolean; atomicRename: boolean; fileFsync: boolean; directoryFsync: boolean; advisoryLock: boolean; caseSensitive: boolean; availableBytes: string | null; requiredBytes: string; blockers: string[] }

type __EventObj__<T> = {
export type ExecuteLifecycleRequest = { operationId: string; planDigest: string }
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
export type IndexRebuildPlan = { operationId: string; planDigest: string; blockers: VaultVerifyIssue[]; skillManifestPaths: string[]; deploymentManifestPaths: string[]; operationJournalPaths: string[]; unresolvedOperationIds: string[] }
export type IndexRebuildResult = { rebuiltSkills: number; rebuiltDeployments: number; rebuiltOperations: number; backupPath: string; restartRequired: boolean }
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

export type LifecycleRecoveryEvidence = { operationId: string; classification: string; blocking: boolean }
export type ManualProjectAddRequest = { selectedPath: string }
export type ManualProjectIdRequest = { projectId: string }
export type ManualProjectView = { projectId: string; rootPath: string; canonicalPath: string; git: boolean }
export type ObjectGcCandidate = { digest: string; exactPath: string; createdAt: string; retentionDeadline: string; pendingOwnerOperationId: string | null }
export type ObjectGcPhase = "stage_pending_delete" | "delete_pending"
export type ObjectGcPlan = { operationId: string; planDigest: string; phase: ObjectGcPhase; enabled: boolean; retentionDays: number; candidates: ObjectGcCandidate[]; blockers: string[]; referencedObjects: number; inspectedObjects: number }
export type ObjectGcPlanRequest = { phase: ObjectGcPhase }
export type ObjectGcResult = { operationId: string; phase: ObjectGcPhase; affectedObjects: number; evidencePath: string }
export type ObjectGcSettingsSummary = { retentionDays: number; lastRun: string | null; eligible: boolean; nextRun: string | null; disabledReasons: string[] }
function __makeEvents__<T extends Record<string, any>>(
export type OldVaultCleanupPlan = { operationId: string; planDigest: string; oldVaultPath: string; activeVaultPath: string; vaultId: string }
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
export type SkillLifecycleRequest = { skillId: string }
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
export type VaultPathRequest = { path: string }
export type VaultRelocatePlan = { operationId: string; planDigest: string; oldVaultPath: string; destinationPath: string; stagingPath: string; vaultId: string; capability: DestinationCapabilityReport }
export type VaultRelocateResult = { operationId: string; oldVaultPath: string; activeVaultPath: string; rewrittenSymlinks: number; restartRequired: boolean; oldVaultRetained: boolean }
export type VaultRepairAction = { kind: string; exactPath: string; reason: string; requiresReviewedOperation: boolean }
export type VaultRepairPlan = { operationId: string; planDigest: string; writable: boolean; actions: VaultRepairAction[]; refused: VaultVerifyIssue[] }
			},
		},
export type VaultVerifyIssue = { code: string; path: string; detail: string; repairable: boolean }
export type VaultVerifyReport = { healthy: boolean; checkedSkills: number; checkedObjects: number; issues: VaultVerifyIssue[] }
export type WorkspaceDiagnosticView = { path: string; code: string; summary: string }
export type WorkspaceProjectBatchEvent = { rootId: string; projectRoot: string; projectKind: string; skillCount: number; errorCount: number; observations: WorkspaceProjectObservationView[]; diagnostics: WorkspaceDiagnosticView[]; batchComplete: boolean }
export type WorkspaceProjectObservationView = { adapterId: string; displayPath: string; status: string }
export type WorkspaceRemoveResult = { rootId: string; removed: boolean; noFilesChanged: boolean }
export type WorkspaceRootAddRequest = { selectedPath: string; maximumDepth: number | null; ignoreRules: string[] }
export type WorkspaceRootIdRequest = { rootId: string }
export type WorkspaceRootPauseRequest = { rootId: string; paused: boolean }
export type WorkspaceRootUpdateRequest = { rootId: string; selectedPath: string | null; maximumDepth: number | null; ignoreRules: string[] | null }
export type WorkspaceRootView = { rootId: string; selectedPath: string; canonicalPath: string; enabled: boolean; paused: boolean; maximumDepth: number; ignoreRules: string[]; coverageState: string; lastAttempt: string | null; lastSuccessfulCompleteScan: string | null; projectCount: number; skillCount: number; errorCount: number; errors: WorkspaceDiagnosticView[]; noFilesChanged: boolean }
export type WorkspaceScanResultView = { rootId: string; coverageState: string; complete: boolean; projectCount: number; skillCount: number; errorCount: number; streamedProjectBatches: number; noFilesChanged: boolean }
	);
}
